# Generated by Django 4.0.3 on 2022-03-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testepratico', '0002_rename_usuario_usuarios_alter_usuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='apelido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='observacao',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
