# Generated by Django 4.0.3 on 2022-03-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testepratico', '0003_usuarios_apelido_usuarios_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apelido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='observacao',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
